# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
enable_theme_toggle: true

# Button Setting
navigation: custom
masthead_links:
  custom: custom-nav

# Site Settings
locale: "en-US"
title: "Teralix42"
title_separator: " "
subtitle: "Building tools no one asked for, but everyone will fear."
name: "Teralix"
description: "15 y/o dev you'll regret ever talking to"
url: "https://teralix42.github.io"
baseurl: ""
repository: "Teralix42/Teralix42.github.io"
enable_copy_code_button: true
search: true

# Author
author:
  name: "Teralix"
  bio: "15 y/o dev, Linux gremlin, Python punk, Powershell hacker."
  location: "Earth (unfortunately)"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Teralix42"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.com/users/1290618095416901663"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Teralix42"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.com/users/1290618095416901663"

# Reading Files
include:
  - .htaccess
  - _pages
  - .well-known
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - tmp
  - "*.sublime-project"
  - "*.sublime-workspace"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Bangkok

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
