# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
enable_theme_toggle: true

enable_copy_code_button: true
search: true

# Head of the page
locale: "en-US"
title: "Teralix42"
title_separator: " "
subtitle: "Building tools no one asked for, but everyone will fear."
logo: /assets/images/logo.png
name: "Teralix"
url: "https://teralix42.github.io"
baseurl: ""
repository: "Teralix42/Teralix42.github.io"

# Author
author:
  name: "Teralix"
  bio: "15 y/o dev, Linux hacker, Python geek, Powershell dependency-hell lover."
  location: "Earth (unfortunately)"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Teralix42"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.com/users/1290618095416901663"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Teralix42"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.com/users/1290618095416901663"

# Reading Files
include:
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Bangkok

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
